### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by jsferreira** [zachgrayio/swift-tensorflow-starter#6]
Hi Zach,

 thanks for starting this project. It can be very useful. 

If we follow your instructions to build the image it will fail with error: "error: root manifest not found"
This happens just after the swift package update. Looking into your Dockerfile it seems that you need to change the order of a few lines. The add/cd to /usr/src must come first than the copy and update of Package.swift.

 ```
# Add Source
ADD ./ /usr/src
WORKDIR /usr/src

# user can pass in CONFIG=release to override
# Cache this step
COPY Package.swift /usr/src
RUN swift package update
```

**Comment by zachgrayio** [comment]
I have the `Dockerfile` copying just the package and then running `swift package update` so that the package and dependencies can be cached in a separate layer, in a desire to optimize build times.

@jsferreira -  It's odd you're seeing an error here; what version of docker and OS are you running? I'm OK with fixing this if needed but I'd like to understand exactly what the issue is first.

**Comment by jsferreira** [comment]
@zachgrayio 

```
$ docker --version
Docker version 18.03.1-ce, build 9ee9f40
$ uname -v
Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
$ docker build -t sts-application .
Sending build context to Docker daemon  146.9kB
Step 1/11 : FROM zachgray/swift-tensorflow:4.2
4.2: Pulling from zachgray/swift-tensorflow
ae79f2514705: Pull complete
c59d01a7e4ca: Pull complete
41ba73a9054d: Pull complete
f1bbfd495cc1: Pull complete
0c346f7223e2: Pull complete
d60f8552428d: Pull complete
3e1327d4e5de: Pull complete
Digest: sha256:3dfa1525f0c4c143f385bc45f3ecbb216f3547d25109417c4d73f1fb9a4293ab
Status: Downloaded newer image for zachgray/swift-tensorflow:4.2
 ---> da03cdc15d43
Step 2/11 : LABEL Description="An STS Application"
 ---> Running in 57e5fae19b39ee
Removing intermediate container 57e5fae19b39
 ---> 502208cbbe6d
Step 3/11 : COPY Package.swift /usr/src
 ---> 3de3e664a469
Step 4/11 : RUN swift package update
 ---> Running in 5b699e63849a
error: root manifest not found
The command '/bin/sh -c swift package update' returned a non-zero code: 1
```

Cheers!

**Comment by zachgrayio** [comment]
Great I'll take a look

**Comment by jsferreira** [comment]
@zachgrayio 

 That fixes the problem  ( branch: feature/fix-docker )
